version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"  # Changed to 3307 on host to avoid conflict
    restart: "no"
